language: bash

dist: trusty

sudo: required

services:
  - docker

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - REPO=dockerframework/laradock-build
    - CGO_ENABLED=0
    - GOOS=linux
    - GOARCH=amd64

before_install:
  - sudo chmod +x ./laradock.sh
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - echo 'DOCKER_OPTS="-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock -s devicemapper"' | sudo tee /etc/default/docker > /dev/null
  - sudo service docker restart
  - sleep 3

script:
  - ./laradock.sh
  