version: '3.2'

services:

#================================================================================================
# CORE-CONSUL
#================================================================================================
  consul:
    image: dockerframework/core-consul
    ports:
      - "8300:8300"       # server RPC
      - "8301:8301"       # serf LAN
      - "8301:8301/udp"   # serf LAN (UDP)
      - "8302:8302"       # serf WAN
      - "8302:8302/udp"   # serf WAN (UDP)
      - "8500:8500"       # HTTP
      - "8501:8501"       # HTTPS
      - "8600:8600"       # DNS
      - "8600:8600/udp"   # DNS (UDP)
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - CONSUL_VERSION=1.0.7
      - CONSULTEMPLATE_VERSION=0.19.4
      - CONSUL_OPTIONS=-server -bootstrap-expect 1 -client 0.0.0.0 -ui    # minimal server options
      - CONSUL_DATACENTER=local                                           # datacenter
      - CONSUL_DOMAIN=consul                                              # domain name
      - CONSUL_ENCRYPT=h2N6R1eyTysjBzzXxAWJvA==                           # encryption key
      - CONSUL_TLS=1                                                      # enable TLS
      - CONSUL_TLSCAFILE=/etc/consul.d/ssl/ca.pem                         # TLS CA certificate file
      - CONSUL_TLSCERTFILE=/etc/consul.d/ssl/server.pem                   # TLS server certificate file
      - CONSUL_TLSKEYFILE=/etc/consul.d/ssl/server-priv-key.pem           # TLS server certificate key file

#================================================================================================
# GRAFANA
#================================================================================================
  grafana:
    restart: always
    image: dockerframework/grafana
    ports:
      - "${GRAFANA_PORT}:3000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA_GRAFANA}:/var/lib/grafana                            # volume for data
    environment:
      - GRAFANA_VERSION=${GRAFANA_VERSION}
      - GF_SERVER_ROOT_URL=${GF_SERVER_ROOT_URL}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_INSTALL_PLUGINS=${GF_INSTALL_PLUGINS}
      - GF_AWS_PROFILES=${GF_AWS_PROFILES}
      - GF_AWS_default_ACCESS_KEY_ID=${GF_AWS_default_ACCESS_KEY_ID}
      - GF_AWS_default_SECRET_ACCESS_KEY=${GF_AWS_default_SECRET_ACCESS_KEY}
      - GF_AWS_default_REGION=${GF_AWS_default_REGION}
            
#================================================================================================
# PORTAINER
#================================================================================================
  portainer:
    restart: always
    build:
      context: .
    ports:
      - "${PORTAINER_PORT}:9000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_PORTAINER}:/data                                      # volume for data
    environment:
      - PORTAINER_VERSION=${PORTAINER_VERSION}
