version: '3.2'

services:

#================================================================================================
# CORE-CONSUL
#================================================================================================
  consul:
    image: dockerframework/core-consul
    container_name: dockerframework_consul
    ports:
      - "8300:8300"       # server RPC
      - "8301:8301"       # serf LAN
      - "8301:8301/udp"   # serf LAN (UDP)
      - "8302:8302"       # serf WAN
      - "8302:8302/udp"   # serf WAN (UDP)
      - "8500:8500"       # HTTP
      - "8501:8501"       # HTTPS
      - "8600:8600"       # DNS
      - "8600:8600/udp"   # DNS (UDP)
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - CONSUL_VERSION=1.0.7
      - CONSULTEMPLATE_VERSION=0.19.4
      - CONSUL_OPTIONS=-server -bootstrap-expect 1 -client 0.0.0.0 -ui    # minimal server options
      - CONSUL_DATACENTER=local                                           # datacenter
      - CONSUL_DOMAIN=consul                                              # domain name
      - CONSUL_ENCRYPT=h2N6R1eyTysjBzzXxAWJvA==                           # encryption key
      - CONSUL_TLS=1                                                      # enable TLS
      - CONSUL_TLSCAFILE=/etc/consul.d/ssl/ca.pem                         # TLS CA certificate file
      - CONSUL_TLSCERTFILE=/etc/consul.d/ssl/server.pem                   # TLS server certificate file
      - CONSUL_TLSKEYFILE=/etc/consul.d/ssl/server-priv-key.pem           # TLS server certificate key file

#================================================================================================
# GRAFANA
#================================================================================================
  grafana:
    restart: unless-stopped
    image: dockerframework/grafana
    container_name: dockerframework_grafana
    ports:
      - "8120:3000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/grafana:/var/lib/grafana                             # volume for data
    environment:
      - GRAFANA_VERSION=5.3.4
      - GF_SERVER_ROOT_URL=http://localhost:8120
      - GF_SECURITY_ADMIN_USER=laradock
      - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app,cloudflare-app,crate-datasource,digiapulssi-breadcrumb-panel,grafana-azure-monitor-datasource,grafana-clock-panel,grafana-simple-json-datasource,grafana-kubernetes-app,grafana-worldmap-panel,percona-percona-app,raintank-worldping-app
      # - GF_AWS_PROFILES=default
      # - GF_AWS_default_ACCESS_KEY_ID=YOUR_ACCESS_KEY
      # - GF_AWS_default_SECRET_ACCESS_KEY=YOUR_SECRET_KEY
      # - GF_AWS_default_REGION=us-east-1

#================================================================================================
# PORTAINER
#================================================================================================
  portainer:
    restart: unless-stopped
    image: dockerframework/portainer
    container_name: dockerframework_portainer
    ports:
      - "8119:9000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/portainer:/data                                      # volume for data
    environment:
      - PORTAINER_VERSION=1.18.1

#================================================================================================
# PROMETHEUS
#================================================================================================
  prometheus:
    restart: unless-stopped
    image: dockerframework/prometheus
    container_name: dockerframework_prometheus
    volumes:
      - ./config/prometheus/alert.rules:/etc/prometheus/alert.rules
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention=200h'
      - '--web.enable-lifecycle'
    ports:
      - "8307:9090"
    labels:
      org.label-schema.group: "monitoring"
    environment:
      - PROMETHEUS_VERSION=2.5.0
