version: '3.2'

services:

#================================================================================================
# CORE-CONSUL
#================================================================================================
  consul:
    image: dockerframework/core-consul
    ports:
      - "8300:8300"       # server RPC
      - "8301:8301"       # serf LAN
      - "8301:8301/udp"   # serf LAN (UDP)
      - "8302:8302"       # serf WAN
      - "8302:8302/udp"   # serf WAN (UDP)
      - "8500:8500"       # HTTP
      - "8501:8501"       # HTTPS
      - "8600:8600"       # DNS
      - "8600:8600/udp"   # DNS (UDP)
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - CONSUL_VERSION=1.0.7
      - CONSULTEMPLATE_VERSION=0.19.4
      - CONSUL_OPTIONS=-server -bootstrap-expect 1 -client 0.0.0.0 -ui    # minimal server options
      - CONSUL_DATACENTER=local                                           # datacenter
      - CONSUL_DOMAIN=consul                                              # domain name
      - CONSUL_ENCRYPT=h2N6R1eyTysjBzzXxAWJvA==                           # encryption key
      - CONSUL_TLS=1                                                      # enable TLS
      - CONSUL_TLSCAFILE=/etc/consul.d/ssl/ca.pem                         # TLS CA certificate file
      - CONSUL_TLSCERTFILE=/etc/consul.d/ssl/server.pem                   # TLS server certificate file
      - CONSUL_TLSKEYFILE=/etc/consul.d/ssl/server-priv-key.pem           # TLS server certificate key file

#================================================================================================
# GRAFANA
#================================================================================================
  grafana:
    restart: always
    image: dockerframework/grafana
    ports:
      - "9100:3000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/grafana:/var/lib/grafana                             # volume for data
    environment:
      - GRAFANA_VERSION=5.1.3
      - GF_SERVER_ROOT_URL=http://localhost:9100
      - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,grafana-worldmap-panel,alexanderzobnin-zabbix-app
      # - GF_AWS_PROFILES=default
      # - GF_AWS_default_ACCESS_KEY_ID=YOUR_ACCESS_KEY
      # - GF_AWS_default_SECRET_ACCESS_KEY=YOUR_SECRET_KEY
      # - GF_AWS_default_REGION=us-east-1

#================================================================================================
# PORTAINER
#================================================================================================
  portainer:
    restart: always
    image: dockerframework/portainer
    ports:
      - "8119:9000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/portainer:/data                                      # volume for data
    environment:
      - PORTAINER_VERSION=1.16.5
